\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename bdsim.info
@settitle BDSIM beta User's Manual
@c This date is automagically updated when you save this file:
@set lastupdate January 20, 2005
@c %**end of header

@setchapternewpage off


@copying

Copyright @copyright{} 2005 Royal Holloway.

@quotation
This code ia an intellectual property of the British Empire.
@end quotation
@end copying


@titlepage
@title BDSIM User's Manual
@author RHUL FLC
@author last updated @value{lastupdate}
@end titlepage
@setcontentsaftertitlepage


@node Top, Intro, (dir), (dir)
@top BDSIM beta User's Manual

This file is updated automatically from @file{bdsim_manual.texi}, which was
last updated on @value{lastupdate}.


@contents
@insertcopying


@menu
* Intro::                       
* Installation::                
* Input::                       
* Physics::                     
* Tracking::                    
* Architecture::                
* Authors::                     
* References::                  
@end menu


@node Intro, Installation, Top, Top
@chapter About BDSIM

BDSIM is a particle tracking code designed for accurate simulation of particle
transport in high energy accelerator beam lines. It combines fast tracking 
techniques in conventional electromagnetic fields with Monte-Carlo simulations of various 
particle interactions. It is intended to use in such problems as collimation
design, background studies, laser beam diagnostics etc. 
 

@node Installation, Input,Intro, Top
@chapter Obtaining, Installing and Running

@code{% cvs loging @* % gmake}



@node Input,Physics,Installation,Top
@chapter Input

@menu
* Cards::                        
* Optics::
@end menu

@node Cards,,,
@section Input Cards


The execution of @code{BDSIM} is controlled by parameters specified in the
input cards file. It has the following format


@var{card-name} @var{card-value}

Possible card names are 

@table @samp

@item ACCELERATOR

Accelerator name

@item BUNCH_TYPE

@item USE_JOB

@item TUNNEL_RADIUS

@item BEAMPIPE_RADIUS

@item TURN_ON_SYNCHROTRON

@end table


@node Optics,,,
@section Optics File

The accelerator components beamline is described in the optics file in the
TFF format (used in MAD8).

@section Output

@node Physics,Tracking,Input,Top
@chapter Physics Processes

@node Tracking,Architecture,Physics,Top
@chapter Tracking

@node Architecture,Authors,Tracking,Top
@chapter Implementation Notes

@node Authors, References, Architecture, Top
@chapter Authors 

@table @code

@item Ilya Agapov @email{agapov@@pp.rhul.ac.uk}
@item Grahame Blair @email{blair@@pp.rhul.ac.uk}
@item John Carter @email{carter@@pp.rhul.ac.uk}

@end table 


@node References, , Authors, Top
@chapter References

@enumerate

@item
G. Blair, SIMULATION OF THE CLIC BEAM DELIVERY SYSTEM USING BDSIM, CLIC Note 509

@item 
Root User's Guide 

@item 
Geant4 User's Guide

@item 
MAD8 User's Guide

@end enumerate

@bye
@c  LocalWords:  dir texi lastupdate uref http www org html helpgnu ifinfo ftp
@c  LocalWords:  dvi hurd toc gvc URL GTK XmHTML xs nl ripley NT com gettext Qt
@c  LocalWords:  GUI libstdc Docbook SGML libc sed STL Gforth GNUstep TCSH Perl
@c  LocalWords:  Ghostscript PIC GCC Texinfo grep dc bc ethernet GDB IP CIFS CU
@c  LocalWords:  SMB SVGA Khoros Automake OpenStep diff roff Smail tron veritas
@c  LocalWords:  cxref ctrace API LilyPond xephem labanotation LessTif outliner
@c  LocalWords:  Hypercard morphing SeeMe ICQ Diffie Helman RSA SSLv TLSv GPL
@c  LocalWords:  OpenBIOS BIOS LILO dbase dbased Harbour harbour WYSIWYG ISBN
@c  LocalWords:  TruePrint Baecker siff sif cs arizona edu TR ps mt sulaco MP
@c  LocalWords:  RTSP MPEG jasonw ariel ucs unimelb AU stutz dsl TCL Javascript
@c  LocalWords:  Rexx GnuGo jhall isd Biomorph regexp eval gd gnuorg
