#!/bin/bash

usage="Usage : bdsimrun [options] \n
       Options: \n
           -c <file>    - use <file> as cards file\n 
           -o <file>    - use <file> as optics file\n
	   -n           - run without Geant4 prompt\n
           -b           - run in batch mode (requires a PBS batch server running)\n
           -N <number>  - number of jobs in batch mode\n
           -r <file>    - get random seeds from file (overrides -N) 
           -h           - display this message "

# TODO:
# " -l <user>@<host> - run batch job on <host> logging in as <user> "


# default parameters
optics_file="optics"
cards_file="BDSInput.cards"
interactive="1"
seed_file=""
jobs_number="1"

while getopts "hvbnu:o:c:r:N:" options; do
  case $options in
    u ) uname=$OPTARG;;
    b ) batch_mode="1";;
    n ) interactive="0";;
    o ) optics_file=$OPTARG;;
    c ) cards_file=$OPTARG;;
    N ) jobs_number=$OPTARG;;
    r)  seed_file=$OPTARG;; 	 
    h ) echo -e $usage
         exit 1;;
    \? ) echo -e $usage
         exit 1;;
    * ) echo -e $usage
          exit 1;;

  esac
done


# PBS batch mode

if [ $batch_mode ]; then
    echo "running in batch mode..."
    run_options="--cards=$cards_file --optics=$optics_file --batch"
    
    qsub=$(which qsub 2> /dev/null)

    jobscript="#!/bin/bash \n
               bdsim $run_options --cards=$cards_file --optics=$optics_file"

    if [[ -x $qsub ]] ; then		

	if [[ "$seed_file" != "" ]] || [[ -f "$seed_file" ]]; then  # the whole file used if specified
	    
	    while read seeds
	      do
	      echo "job $i : using seed from file $seed_file : $seeds"
	      echo -e $jobscript | qsub -q medium -v BDS_SEED=$seeds,BDS_FILENAME=bdsim_out$i -N bdsim$i 
	    done < $seed_file
	else

	    for ((i=1; i<$jobs_number;i=i+1)); do
		seeds=$RANDOM
		echo "job $i : using seed  : $seeds"
		echo -e $jobscript | qsub -q medium -v BDS_SEED=$seeds,BDS_FILENAME=bdsim_out$i -N bdsim$i 
	    done

	fi
	
    else
	echo "Error: I can't find qsub on your computer, quitting "
    fi
    
    
    exit 0
fi

# noninteractive
if [ "$interactive" == "0" ]; then
    run_options="--batch --cards=$cards_file --optics=$optics_file"
    bdsim $run_options
    exit 0
fi

# default - interactive mode 

run_options="--cards=$cards_file --optics=$optics_file"
echo "running in interactivemode..."

bdsim $run_options



