/vis/open OGLIX
#/vis/open DAWNFILE

# Create an empty scene 
/vis/scene/create

# Add detector geometry to the current scene
/vis/scene/add/volume

# Attach the current scene handler 
# to the current scene (omittable)
/vis/sceneHandler/attach


/vis/viewer/set/background white
/vis/viewer/set/viewpointThetaPhi 90 89.99
/vis/viewer/zoom 12
/vis/viewer/pan -40 0
/vis/viewer/scaleTo 1 30 1
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
