# ALL LENGTHS MUST BE GIVEN IN MILLIMETRES
# ALL ROTATIONS MUST BE GIVEN IN RADIANS

DROP DATABASE IF EXISTS TORUSTEST;
CREATE DATABASE TORUSTEST;
USE TORUSTEST;

CREATE TABLE MYTEST_TRAP (
    PARENTNAME    VARCHAR(32), #
    POSX          DOUBLE(10,3), #
    POSY          DOUBLE(10,3), #
    POSZ          DOUBLE(10,3), #
    RED           DOUBLE(10,3), #
    GREEN         DOUBLE(10,3), #
    BLUE          DOUBLE(10,3), #
    VISATT        VARCHAR(32),  # I = INVISIBLE, S = SOLID, W = WIREFRAME
    LENGTHXPLUS   DOUBLE(10,3), #
    LENGTHXMINUS  DOUBLE(10,3), #
    LENGTHYPLUS   DOUBLE(10,3), #
    LENGTHYMINUS  DOUBLE(10,3), #
    LENGTHZ       DOUBLE(10,3), #
    ROTPSI        DOUBLE(10,3), #
    ROTTHETA      DOUBLE(10,3), #
    ROTPHI        DOUBLE(10,3), #
    FIELDX        DOUBLE(10,3), #
    MATERIAL      VARCHAR(32),  # MATERIAL, CGA LITERAL NAME
    NAME          VARCHAR(32)   # NAME OF SOLID, LOGICAL, AND PHYSICAL VOLUME
);

INSERT INTO MYTEST_TRAP VALUES ("",0.,0., 750, 0., 0.,1.0,"S",200, 400,300 , 300, 1000, 0. ,0.0,0,5, "vacuum","A_TRAP");
