/********************************************************************
* ../src/BDSOutputROOTEventSamplerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/BDSOutputROOTEventSamplerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBDSOutputROOTEventSamplerDict();
extern void G__cpp_setup_inheritanceBDSOutputROOTEventSamplerDict();
extern void G__cpp_setup_typetableBDSOutputROOTEventSamplerDict();
extern void G__cpp_setup_memvarBDSOutputROOTEventSamplerDict();
extern void G__cpp_setup_globalBDSOutputROOTEventSamplerDict();
extern void G__cpp_setup_memfuncBDSOutputROOTEventSamplerDict();
extern void G__cpp_setup_funcBDSOutputROOTEventSamplerDict();
extern void G__set_cpp_environmentBDSOutputROOTEventSamplerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BDSOutputROOTEventSampler.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_TClass;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_TBuffer;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_TMemberInspector;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_TObject;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_string;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_BDSOutputROOTEventSampler;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BDSOutputROOTEventSamplerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
