/********************************************************************
* mydict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mydict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablemydict();
extern void G__cpp_setup_inheritancemydict();
extern void G__cpp_setup_typetablemydict();
extern void G__cpp_setup_memvarmydict();
extern void G__cpp_setup_globalmydict();
extern void G__cpp_setup_memfuncmydict();
extern void G__cpp_setup_funcmydict();
extern void G__set_cpp_environmentmydict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "BDSCanvas.h"
#include "BDSPad.h"
#include "BDSAxis.h"
#include "BDSParser.h"
#include "BDSBox.h"
#include "BDSPopUp.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mydictLN_TClass;
extern G__linked_taginfo G__mydictLN_TBuffer;
extern G__linked_taginfo G__mydictLN_TMemberInspector;
extern G__linked_taginfo G__mydictLN_TObject;
extern G__linked_taginfo G__mydictLN_TList;
extern G__linked_taginfo G__mydictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__mydictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__mydictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mydictLN_TString;
extern G__linked_taginfo G__mydictLN_TVirtualPad;
extern G__linked_taginfo G__mydictLN_TAttPad;
extern G__linked_taginfo G__mydictLN_TAttLine;
extern G__linked_taginfo G__mydictLN_TAttFill;
extern G__linked_taginfo G__mydictLN_TAttText;
extern G__linked_taginfo G__mydictLN_TQObject;
extern G__linked_taginfo G__mydictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__mydictLN_TCanvas;
extern G__linked_taginfo G__mydictLN_TH1F;
extern G__linked_taginfo G__mydictLN_TBox;
extern G__linked_taginfo G__mydictLN_TPad;
extern G__linked_taginfo G__mydictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__mydictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__mydictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__mydictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__mydictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__mydictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mydictLN_BDSPad;
extern G__linked_taginfo G__mydictLN_BDSCanvas;
extern G__linked_taginfo G__mydictLN_Element;
extern G__linked_taginfo G__mydictLN_listlEElementcOallocatorlEElementgRsPgR;
extern G__linked_taginfo G__mydictLN_TClassMenuItem;
extern G__linked_taginfo G__mydictLN_BDSAxis;
extern G__linked_taginfo G__mydictLN_TLine;
extern G__linked_taginfo G__mydictLN_TGaxis;
extern G__linked_taginfo G__mydictLN_BDSParser;
extern G__linked_taginfo G__mydictLN_BDSBox;
extern G__linked_taginfo G__mydictLN_BDSPopUp;

/* STUB derived class for protected member access */
